#CVE编号:CVE-2014-3566
#Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
#encoding:GBK
import ssl,socket,sys

def check_ssl_vesion(url="",port=443,ssl_version="SSLv23"):

    SSL_VERSION={
        #"SSLv2":ssl.PROTOCOL_SSLv2,
        "SSLv3":ssl.PROTOCOL_SSLv3,
        "SSLv23":ssl.PROTOCOL_SSLv23,
        "TLSv1":ssl.PROTOCOL_TLSv1,
        "TLSv1.1":ssl.PROTOCOL_TLSv1_1,
        "TLSv1.2":ssl.PROTOCOL_TLSv1_2,
        }
   
    try:
        ssl_version_config= ssl.SSLSocket(socket.socket(),ssl_version=SSL_VERSION.get(ssl_version)) # 设置ssl客户端版本
        response=ssl_version_config.connect((url,port)) #使用https连接
        print("支持"+ssl_version)
        return True
    except Exception as e:
        #print(e)
        print("不支持"+ssl_version)
        return False
    
  
def disview():
    print '''
*******************POC*************************************
'''
    print("漏洞名称：")
    print("SSLv3存在严重设计缺陷漏洞（CVE-2014-3566）")
    print("漏洞详细描述：")
    print'''SSLv3漏洞（CVE-2014-3566），该漏洞贯穿于所有的SSLv3版本中，利用该漏洞，黑客可以通过中间人攻击等类似的方式(只要劫持到的数据加密两端均使用SSL3.0)，便可以成功获取到传输数据(例如cookies)。针对此漏洞，需要服务器端和客户端均停用SSLv3协议。
'''

if __name__=="__main__":


 '''
# 使用说明：pyhon cve-2014-3566_poc.py www.baidu.com 443
    try:
        url =sys.argv[1]
    except Exception as e:
        print e
    try:
        port =int(sys.argv[2])
    except Exception as e:
        port=443
    '''
 
    url  = "www.baidu.com"   #设置访问URL:例子www.baidu.com
    port = 443  #设置HTTPS访问网站端口


    disview()

    try:
        print("-------------------------------")
        print("网站："+url)
        print("SSL通讯协议支持检查")
        
        print("-------------------------------")
        #sslv2=check_ssl_vesion(url,port,'SSLv2')
        sslv3=check_ssl_vesion(url,port,'SSLv3')
        sslv23=check_ssl_vesion(url,port,'SSLv23')
        tls1=check_ssl_vesion(url,port,'TLSv1')
        tls1_1=check_ssl_vesion(url,port,'TLSv1.1')
        tls1_2=check_ssl_vesion(url,port,'TLSv1.2')
        print("-------------------------------")
    except Exception as e:
        print(e)
    
